package com.fdays.tsms.airticket._entity;



/**
 * Airline generated by hbm2java
 */


public class _Airline 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String begin;
     protected String end;
     protected Long price;
     protected Long status;
     protected Long distance;
     protected java.util.Set airlinePlaces = new java.util.HashSet(0);

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getBegin() {
        return this.begin;
    }
    
    public void setBegin(String begin) {
        this.begin = begin;
    }
    


    public String getEnd() {
        return this.end;
    }
    
    public void setEnd(String end) {
        this.end = end;
    }
    


    public Long getPrice() {
        return this.price;
    }
    
    public void setPrice(Long price) {
        this.price = price;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public Long getDistance() {
        return this.distance;
    }
    
    public void setDistance(Long distance) {
        this.distance = distance;
    }
    


    public java.util.Set getAirlinePlaces() {
        return this.airlinePlaces;
    }
    
    public void setAirlinePlaces(java.util.Set airlinePlaces) {
        this.airlinePlaces = airlinePlaces;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


