package com.fdays.tsms.airticket._entity;



/**
 * AirticketOrder generated by hbm2java
 */


public class _AirticketOrder 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String airOrderNo;
     protected Long subGroupMarkNo;
     protected String drawPnr;
     protected String subPnr;
     protected String bigPnr;
     protected String umbuchenPnr;
     protected java.math.BigDecimal ticketPrice;
     protected java.math.BigDecimal rebate;
     protected Long adultCount;
     protected Long childCount;
     protected Long babyCount;
     protected java.math.BigDecimal airportPrice;
     protected java.math.BigDecimal fuelPrice;
     protected java.math.BigDecimal documentPrice;
     protected java.math.BigDecimal insurancePrice;
     protected java.math.BigDecimal handlingCharge;
     protected String entryOperator;
     protected String payOperator;
     protected String currentOperator;
     protected String drawer;
     protected Long ticketType;
     protected Long tranType;
     protected Long businessType;
     protected java.sql.Timestamp entryTime;
     protected java.sql.Timestamp payTime;
     protected java.sql.Timestamp optTime;
     protected java.sql.Timestamp drawTime;
     protected String memo;
     protected Long status;
     protected java.math.BigDecimal totalTicketPrice;
     protected java.math.BigDecimal totalAirportPrice;
     protected java.math.BigDecimal totalFuelPrice;
     protected java.math.BigDecimal proxyPrice;
     protected java.math.BigDecimal incomeretreatCharge;
     protected java.math.BigDecimal overTicketPrice;
     protected java.math.BigDecimal overAirportfulePrice;
     protected java.math.BigDecimal teamaddPrice;
     protected java.math.BigDecimal agentaddPrice;
     protected java.math.BigDecimal commissonCount;
     protected java.math.BigDecimal rakeoffCount;
     protected String returnReason;
     protected java.math.BigDecimal transRule;
     protected String oldOrderNo;
     protected java.math.BigDecimal totalAmount;
     protected java.math.BigDecimal commission;
     protected java.math.BigDecimal rakeOff;
     protected java.math.BigDecimal unsettledAccount;
     protected String operate1;
     protected java.sql.Timestamp operate1Time;
     protected String operate2;
     protected java.sql.Timestamp operate2Time;
     protected String operate4;
     protected java.sql.Timestamp operate4Time;
     protected String operate5;
     protected java.sql.Timestamp operate5Time;
     protected String operate13;
     protected java.sql.Timestamp operate13Time;
     protected String operate14;
     protected java.sql.Timestamp operate14Time;
     protected String operate15;
     protected java.sql.Timestamp operate15Time;
     protected String operate16;
     protected java.sql.Timestamp operate16Time;
     protected String operate17;
     protected java.sql.Timestamp operate17Time;
     protected String operate20;
     protected java.sql.Timestamp operate20Time;
     protected String operate21;
     protected java.sql.Timestamp operate21Time;
     protected String operate35;
     protected java.sql.Timestamp operate35Time;
     protected String operate40;
     protected java.sql.Timestamp operate40Time;
     protected String operate41;
     protected java.sql.Timestamp operate41Time;
     protected String operate42;
     protected java.sql.Timestamp operate42Time;
     protected String operate43;
     protected java.sql.Timestamp operate43Time;
     protected String operate51;
     protected java.sql.Timestamp operate51Time;
     protected String operate52;
     protected java.sql.Timestamp operate52Time;
     protected String operate53;
     protected java.sql.Timestamp operate53Time;
     protected String operate54;
     protected java.sql.Timestamp operate54Time;
     protected String operate55;
     protected java.sql.Timestamp operate55Time;
     protected String operate88;
     protected java.sql.Timestamp operate88Time;
     protected String orderNo;
     protected String operate100;
     protected java.sql.Timestamp operate100Time;
     protected String operate101;
     protected java.sql.Timestamp operate101Time;
     protected String operate102;
     protected java.sql.Timestamp operate102Time;
     protected String operate103;
     protected java.sql.Timestamp operate103Time;
     protected String operate104;
     protected java.sql.Timestamp operate104Time;
     protected String operate105;
     protected java.sql.Timestamp operate105Time;
     protected String operate106;
     protected java.sql.Timestamp operate106Time;
     protected String operate107;
     protected java.sql.Timestamp operate107Time;
     protected String operate108;
     protected java.sql.Timestamp operate108Time;
     protected String operate109;
     protected java.sql.Timestamp operate109Time;
     protected String operate110;
     protected java.sql.Timestamp operate110Time;
     protected String operate117;
     protected java.sql.Timestamp operate117Time;
     protected String operate121;
     protected java.sql.Timestamp operate121Time;
     protected java.sql.Timestamp operate203Time;
     protected String operate122;
     protected String operate125;
     protected java.sql.Timestamp operate125Time;
     protected String operate126;
     protected java.sql.Timestamp operate126Time;
     protected String operate127;
     protected java.sql.Timestamp operate127Time;
     protected String operate201;
     protected java.sql.Timestamp operate201Time;
     protected String operate202;
     protected java.sql.Timestamp operate202Time;
     protected String operate203;
     protected java.sql.Timestamp operate122Time;
     protected Long locked;
     protected java.sql.Timestamp createDate;
     protected java.util.Set flights = new java.util.HashSet(0);
     protected java.util.Set passengers = new java.util.HashSet(0);
     protected com.fdays.tsms.transaction.Agent agent;
     protected com.fdays.tsms.transaction.Platform platform;
     protected com.fdays.tsms.transaction.Company company;
     protected com.fdays.tsms.transaction.Account account;
     protected com.fdays.tsms.airticket.OrderGroup orderGroup;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getAirOrderNo() {
        return this.airOrderNo;
    }
    
    public void setAirOrderNo(String airOrderNo) {
        this.airOrderNo = airOrderNo;
    }
    


    public Long getSubGroupMarkNo() {
        return this.subGroupMarkNo;
    }
    
    public void setSubGroupMarkNo(Long subGroupMarkNo) {
        this.subGroupMarkNo = subGroupMarkNo;
    }
    


    public String getDrawPnr() {
        return this.drawPnr;
    }
    
    public void setDrawPnr(String drawPnr) {
        this.drawPnr = drawPnr;
    }
    


    public String getSubPnr() {
        return this.subPnr;
    }
    
    public void setSubPnr(String subPnr) {
        this.subPnr = subPnr;
    }
    


    public String getBigPnr() {
        return this.bigPnr;
    }
    
    public void setBigPnr(String bigPnr) {
        this.bigPnr = bigPnr;
    }
    


    public String getUmbuchenPnr() {
        return this.umbuchenPnr;
    }
    
    public void setUmbuchenPnr(String umbuchenPnr) {
        this.umbuchenPnr = umbuchenPnr;
    }
    


    public java.math.BigDecimal getTicketPrice() {
        return this.ticketPrice;
    }
    
    public void setTicketPrice(java.math.BigDecimal ticketPrice) {
        this.ticketPrice = ticketPrice;
    }
    


    public java.math.BigDecimal getRebate() {
        return this.rebate;
    }
    
    public void setRebate(java.math.BigDecimal rebate) {
        this.rebate = rebate;
    }
    


    public Long getAdultCount() {
        return this.adultCount;
    }
    
    public void setAdultCount(Long adultCount) {
        this.adultCount = adultCount;
    }
    


    public Long getChildCount() {
        return this.childCount;
    }
    
    public void setChildCount(Long childCount) {
        this.childCount = childCount;
    }
    


    public Long getBabyCount() {
        return this.babyCount;
    }
    
    public void setBabyCount(Long babyCount) {
        this.babyCount = babyCount;
    }
    


    public java.math.BigDecimal getAirportPrice() {
        return this.airportPrice;
    }
    
    public void setAirportPrice(java.math.BigDecimal airportPrice) {
        this.airportPrice = airportPrice;
    }
    


    public java.math.BigDecimal getFuelPrice() {
        return this.fuelPrice;
    }
    
    public void setFuelPrice(java.math.BigDecimal fuelPrice) {
        this.fuelPrice = fuelPrice;
    }
    


    public java.math.BigDecimal getDocumentPrice() {
        return this.documentPrice;
    }
    
    public void setDocumentPrice(java.math.BigDecimal documentPrice) {
        this.documentPrice = documentPrice;
    }
    


    public java.math.BigDecimal getInsurancePrice() {
        return this.insurancePrice;
    }
    
    public void setInsurancePrice(java.math.BigDecimal insurancePrice) {
        this.insurancePrice = insurancePrice;
    }
    


    public java.math.BigDecimal getHandlingCharge() {
        return this.handlingCharge;
    }
    
    public void setHandlingCharge(java.math.BigDecimal handlingCharge) {
        this.handlingCharge = handlingCharge;
    }
    


    public String getEntryOperator() {
        return this.entryOperator;
    }
    
    public void setEntryOperator(String entryOperator) {
        this.entryOperator = entryOperator;
    }
    


    public String getPayOperator() {
        return this.payOperator;
    }
    
    public void setPayOperator(String payOperator) {
        this.payOperator = payOperator;
    }
    


    public String getCurrentOperator() {
        return this.currentOperator;
    }
    
    public void setCurrentOperator(String currentOperator) {
        this.currentOperator = currentOperator;
    }
    


    public String getDrawer() {
        return this.drawer;
    }
    
    public void setDrawer(String drawer) {
        this.drawer = drawer;
    }
    


    public Long getTicketType() {
        return this.ticketType;
    }
    
    public void setTicketType(Long ticketType) {
        this.ticketType = ticketType;
    }
    


    public Long getTranType() {
        return this.tranType;
    }
    
    public void setTranType(Long tranType) {
        this.tranType = tranType;
    }
    


    public Long getBusinessType() {
        return this.businessType;
    }
    
    public void setBusinessType(Long businessType) {
        this.businessType = businessType;
    }
    


    public java.sql.Timestamp getEntryTime() {
        return this.entryTime;
    }
    
    public void setEntryTime(java.sql.Timestamp entryTime) {
        this.entryTime = entryTime;
    }
    


    public java.sql.Timestamp getPayTime() {
        return this.payTime;
    }
    
    public void setPayTime(java.sql.Timestamp payTime) {
        this.payTime = payTime;
    }
    


    public java.sql.Timestamp getOptTime() {
        return this.optTime;
    }
    
    public void setOptTime(java.sql.Timestamp optTime) {
        this.optTime = optTime;
    }
    


    public java.sql.Timestamp getDrawTime() {
        return this.drawTime;
    }
    
    public void setDrawTime(java.sql.Timestamp drawTime) {
        this.drawTime = drawTime;
    }
    


    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public java.math.BigDecimal getTotalTicketPrice() {
        return this.totalTicketPrice;
    }
    
    public void setTotalTicketPrice(java.math.BigDecimal totalTicketPrice) {
        this.totalTicketPrice = totalTicketPrice;
    }
    


    public java.math.BigDecimal getTotalAirportPrice() {
        return this.totalAirportPrice;
    }
    
    public void setTotalAirportPrice(java.math.BigDecimal totalAirportPrice) {
        this.totalAirportPrice = totalAirportPrice;
    }
    


    public java.math.BigDecimal getTotalFuelPrice() {
        return this.totalFuelPrice;
    }
    
    public void setTotalFuelPrice(java.math.BigDecimal totalFuelPrice) {
        this.totalFuelPrice = totalFuelPrice;
    }
    


    public java.math.BigDecimal getProxyPrice() {
        return this.proxyPrice;
    }
    
    public void setProxyPrice(java.math.BigDecimal proxyPrice) {
        this.proxyPrice = proxyPrice;
    }
    


    public java.math.BigDecimal getIncomeretreatCharge() {
        return this.incomeretreatCharge;
    }
    
    public void setIncomeretreatCharge(java.math.BigDecimal incomeretreatCharge) {
        this.incomeretreatCharge = incomeretreatCharge;
    }
    


    public java.math.BigDecimal getOverTicketPrice() {
        return this.overTicketPrice;
    }
    
    public void setOverTicketPrice(java.math.BigDecimal overTicketPrice) {
        this.overTicketPrice = overTicketPrice;
    }
    


    public java.math.BigDecimal getOverAirportfulePrice() {
        return this.overAirportfulePrice;
    }
    
    public void setOverAirportfulePrice(java.math.BigDecimal overAirportfulePrice) {
        this.overAirportfulePrice = overAirportfulePrice;
    }
    


    public java.math.BigDecimal getTeamaddPrice() {
        return this.teamaddPrice;
    }
    
    public void setTeamaddPrice(java.math.BigDecimal teamaddPrice) {
        this.teamaddPrice = teamaddPrice;
    }
    


    public java.math.BigDecimal getAgentaddPrice() {
        return this.agentaddPrice;
    }
    
    public void setAgentaddPrice(java.math.BigDecimal agentaddPrice) {
        this.agentaddPrice = agentaddPrice;
    }
    


    public java.math.BigDecimal getCommissonCount() {
        return this.commissonCount;
    }
    
    public void setCommissonCount(java.math.BigDecimal commissonCount) {
        this.commissonCount = commissonCount;
    }
    


    public java.math.BigDecimal getRakeoffCount() {
        return this.rakeoffCount;
    }
    
    public void setRakeoffCount(java.math.BigDecimal rakeoffCount) {
        this.rakeoffCount = rakeoffCount;
    }
    


    public String getReturnReason() {
        return this.returnReason;
    }
    
    public void setReturnReason(String returnReason) {
        this.returnReason = returnReason;
    }
    


    public java.math.BigDecimal getTransRule() {
        return this.transRule;
    }
    
    public void setTransRule(java.math.BigDecimal transRule) {
        this.transRule = transRule;
    }
    


    public String getOldOrderNo() {
        return this.oldOrderNo;
    }
    
    public void setOldOrderNo(String oldOrderNo) {
        this.oldOrderNo = oldOrderNo;
    }
    


    public java.math.BigDecimal getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(java.math.BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }
    


    public java.math.BigDecimal getCommission() {
        return this.commission;
    }
    
    public void setCommission(java.math.BigDecimal commission) {
        this.commission = commission;
    }
    


    public java.math.BigDecimal getRakeOff() {
        return this.rakeOff;
    }
    
    public void setRakeOff(java.math.BigDecimal rakeOff) {
        this.rakeOff = rakeOff;
    }
    


    public java.math.BigDecimal getUnsettledAccount() {
        return this.unsettledAccount;
    }
    
    public void setUnsettledAccount(java.math.BigDecimal unsettledAccount) {
        this.unsettledAccount = unsettledAccount;
    }
    


    public String getOperate1() {
        return this.operate1;
    }
    
    public void setOperate1(String operate1) {
        this.operate1 = operate1;
    }
    


    public java.sql.Timestamp getOperate1Time() {
        return this.operate1Time;
    }
    
    public void setOperate1Time(java.sql.Timestamp operate1Time) {
        this.operate1Time = operate1Time;
    }
    


    public String getOperate2() {
        return this.operate2;
    }
    
    public void setOperate2(String operate2) {
        this.operate2 = operate2;
    }
    


    public java.sql.Timestamp getOperate2Time() {
        return this.operate2Time;
    }
    
    public void setOperate2Time(java.sql.Timestamp operate2Time) {
        this.operate2Time = operate2Time;
    }
    


    public String getOperate4() {
        return this.operate4;
    }
    
    public void setOperate4(String operate4) {
        this.operate4 = operate4;
    }
    


    public java.sql.Timestamp getOperate4Time() {
        return this.operate4Time;
    }
    
    public void setOperate4Time(java.sql.Timestamp operate4Time) {
        this.operate4Time = operate4Time;
    }
    


    public String getOperate5() {
        return this.operate5;
    }
    
    public void setOperate5(String operate5) {
        this.operate5 = operate5;
    }
    


    public java.sql.Timestamp getOperate5Time() {
        return this.operate5Time;
    }
    
    public void setOperate5Time(java.sql.Timestamp operate5Time) {
        this.operate5Time = operate5Time;
    }
    


    public String getOperate13() {
        return this.operate13;
    }
    
    public void setOperate13(String operate13) {
        this.operate13 = operate13;
    }
    


    public java.sql.Timestamp getOperate13Time() {
        return this.operate13Time;
    }
    
    public void setOperate13Time(java.sql.Timestamp operate13Time) {
        this.operate13Time = operate13Time;
    }
    


    public String getOperate14() {
        return this.operate14;
    }
    
    public void setOperate14(String operate14) {
        this.operate14 = operate14;
    }
    


    public java.sql.Timestamp getOperate14Time() {
        return this.operate14Time;
    }
    
    public void setOperate14Time(java.sql.Timestamp operate14Time) {
        this.operate14Time = operate14Time;
    }
    


    public String getOperate15() {
        return this.operate15;
    }
    
    public void setOperate15(String operate15) {
        this.operate15 = operate15;
    }
    


    public java.sql.Timestamp getOperate15Time() {
        return this.operate15Time;
    }
    
    public void setOperate15Time(java.sql.Timestamp operate15Time) {
        this.operate15Time = operate15Time;
    }
    


    public String getOperate16() {
        return this.operate16;
    }
    
    public void setOperate16(String operate16) {
        this.operate16 = operate16;
    }
    


    public java.sql.Timestamp getOperate16Time() {
        return this.operate16Time;
    }
    
    public void setOperate16Time(java.sql.Timestamp operate16Time) {
        this.operate16Time = operate16Time;
    }
    


    public String getOperate17() {
        return this.operate17;
    }
    
    public void setOperate17(String operate17) {
        this.operate17 = operate17;
    }
    


    public java.sql.Timestamp getOperate17Time() {
        return this.operate17Time;
    }
    
    public void setOperate17Time(java.sql.Timestamp operate17Time) {
        this.operate17Time = operate17Time;
    }
    


    public String getOperate20() {
        return this.operate20;
    }
    
    public void setOperate20(String operate20) {
        this.operate20 = operate20;
    }
    


    public java.sql.Timestamp getOperate20Time() {
        return this.operate20Time;
    }
    
    public void setOperate20Time(java.sql.Timestamp operate20Time) {
        this.operate20Time = operate20Time;
    }
    


    public String getOperate21() {
        return this.operate21;
    }
    
    public void setOperate21(String operate21) {
        this.operate21 = operate21;
    }
    


    public java.sql.Timestamp getOperate21Time() {
        return this.operate21Time;
    }
    
    public void setOperate21Time(java.sql.Timestamp operate21Time) {
        this.operate21Time = operate21Time;
    }
    


    public String getOperate35() {
        return this.operate35;
    }
    
    public void setOperate35(String operate35) {
        this.operate35 = operate35;
    }
    


    public java.sql.Timestamp getOperate35Time() {
        return this.operate35Time;
    }
    
    public void setOperate35Time(java.sql.Timestamp operate35Time) {
        this.operate35Time = operate35Time;
    }
    


    public String getOperate40() {
        return this.operate40;
    }
    
    public void setOperate40(String operate40) {
        this.operate40 = operate40;
    }
    


    public java.sql.Timestamp getOperate40Time() {
        return this.operate40Time;
    }
    
    public void setOperate40Time(java.sql.Timestamp operate40Time) {
        this.operate40Time = operate40Time;
    }
    


    public String getOperate41() {
        return this.operate41;
    }
    
    public void setOperate41(String operate41) {
        this.operate41 = operate41;
    }
    


    public java.sql.Timestamp getOperate41Time() {
        return this.operate41Time;
    }
    
    public void setOperate41Time(java.sql.Timestamp operate41Time) {
        this.operate41Time = operate41Time;
    }
    


    public String getOperate42() {
        return this.operate42;
    }
    
    public void setOperate42(String operate42) {
        this.operate42 = operate42;
    }
    


    public java.sql.Timestamp getOperate42Time() {
        return this.operate42Time;
    }
    
    public void setOperate42Time(java.sql.Timestamp operate42Time) {
        this.operate42Time = operate42Time;
    }
    


    public String getOperate43() {
        return this.operate43;
    }
    
    public void setOperate43(String operate43) {
        this.operate43 = operate43;
    }
    


    public java.sql.Timestamp getOperate43Time() {
        return this.operate43Time;
    }
    
    public void setOperate43Time(java.sql.Timestamp operate43Time) {
        this.operate43Time = operate43Time;
    }
    


    public String getOperate51() {
        return this.operate51;
    }
    
    public void setOperate51(String operate51) {
        this.operate51 = operate51;
    }
    


    public java.sql.Timestamp getOperate51Time() {
        return this.operate51Time;
    }
    
    public void setOperate51Time(java.sql.Timestamp operate51Time) {
        this.operate51Time = operate51Time;
    }
    


    public String getOperate52() {
        return this.operate52;
    }
    
    public void setOperate52(String operate52) {
        this.operate52 = operate52;
    }
    


    public java.sql.Timestamp getOperate52Time() {
        return this.operate52Time;
    }
    
    public void setOperate52Time(java.sql.Timestamp operate52Time) {
        this.operate52Time = operate52Time;
    }
    


    public String getOperate53() {
        return this.operate53;
    }
    
    public void setOperate53(String operate53) {
        this.operate53 = operate53;
    }
    


    public java.sql.Timestamp getOperate53Time() {
        return this.operate53Time;
    }
    
    public void setOperate53Time(java.sql.Timestamp operate53Time) {
        this.operate53Time = operate53Time;
    }
    


    public String getOperate54() {
        return this.operate54;
    }
    
    public void setOperate54(String operate54) {
        this.operate54 = operate54;
    }
    


    public java.sql.Timestamp getOperate54Time() {
        return this.operate54Time;
    }
    
    public void setOperate54Time(java.sql.Timestamp operate54Time) {
        this.operate54Time = operate54Time;
    }
    


    public String getOperate55() {
        return this.operate55;
    }
    
    public void setOperate55(String operate55) {
        this.operate55 = operate55;
    }
    


    public java.sql.Timestamp getOperate55Time() {
        return this.operate55Time;
    }
    
    public void setOperate55Time(java.sql.Timestamp operate55Time) {
        this.operate55Time = operate55Time;
    }
    


    public String getOperate88() {
        return this.operate88;
    }
    
    public void setOperate88(String operate88) {
        this.operate88 = operate88;
    }
    


    public java.sql.Timestamp getOperate88Time() {
        return this.operate88Time;
    }
    
    public void setOperate88Time(java.sql.Timestamp operate88Time) {
        this.operate88Time = operate88Time;
    }
    


    public String getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }
    


    public String getOperate100() {
        return this.operate100;
    }
    
    public void setOperate100(String operate100) {
        this.operate100 = operate100;
    }
    


    public java.sql.Timestamp getOperate100Time() {
        return this.operate100Time;
    }
    
    public void setOperate100Time(java.sql.Timestamp operate100Time) {
        this.operate100Time = operate100Time;
    }
    


    public String getOperate101() {
        return this.operate101;
    }
    
    public void setOperate101(String operate101) {
        this.operate101 = operate101;
    }
    


    public java.sql.Timestamp getOperate101Time() {
        return this.operate101Time;
    }
    
    public void setOperate101Time(java.sql.Timestamp operate101Time) {
        this.operate101Time = operate101Time;
    }
    


    public String getOperate102() {
        return this.operate102;
    }
    
    public void setOperate102(String operate102) {
        this.operate102 = operate102;
    }
    


    public java.sql.Timestamp getOperate102Time() {
        return this.operate102Time;
    }
    
    public void setOperate102Time(java.sql.Timestamp operate102Time) {
        this.operate102Time = operate102Time;
    }
    


    public String getOperate103() {
        return this.operate103;
    }
    
    public void setOperate103(String operate103) {
        this.operate103 = operate103;
    }
    


    public java.sql.Timestamp getOperate103Time() {
        return this.operate103Time;
    }
    
    public void setOperate103Time(java.sql.Timestamp operate103Time) {
        this.operate103Time = operate103Time;
    }
    


    public String getOperate104() {
        return this.operate104;
    }
    
    public void setOperate104(String operate104) {
        this.operate104 = operate104;
    }
    


    public java.sql.Timestamp getOperate104Time() {
        return this.operate104Time;
    }
    
    public void setOperate104Time(java.sql.Timestamp operate104Time) {
        this.operate104Time = operate104Time;
    }
    


    public String getOperate105() {
        return this.operate105;
    }
    
    public void setOperate105(String operate105) {
        this.operate105 = operate105;
    }
    


    public java.sql.Timestamp getOperate105Time() {
        return this.operate105Time;
    }
    
    public void setOperate105Time(java.sql.Timestamp operate105Time) {
        this.operate105Time = operate105Time;
    }
    


    public String getOperate106() {
        return this.operate106;
    }
    
    public void setOperate106(String operate106) {
        this.operate106 = operate106;
    }
    


    public java.sql.Timestamp getOperate106Time() {
        return this.operate106Time;
    }
    
    public void setOperate106Time(java.sql.Timestamp operate106Time) {
        this.operate106Time = operate106Time;
    }
    


    public String getOperate107() {
        return this.operate107;
    }
    
    public void setOperate107(String operate107) {
        this.operate107 = operate107;
    }
    


    public java.sql.Timestamp getOperate107Time() {
        return this.operate107Time;
    }
    
    public void setOperate107Time(java.sql.Timestamp operate107Time) {
        this.operate107Time = operate107Time;
    }
    


    public String getOperate108() {
        return this.operate108;
    }
    
    public void setOperate108(String operate108) {
        this.operate108 = operate108;
    }
    


    public java.sql.Timestamp getOperate108Time() {
        return this.operate108Time;
    }
    
    public void setOperate108Time(java.sql.Timestamp operate108Time) {
        this.operate108Time = operate108Time;
    }
    


    public String getOperate109() {
        return this.operate109;
    }
    
    public void setOperate109(String operate109) {
        this.operate109 = operate109;
    }
    


    public java.sql.Timestamp getOperate109Time() {
        return this.operate109Time;
    }
    
    public void setOperate109Time(java.sql.Timestamp operate109Time) {
        this.operate109Time = operate109Time;
    }
    


    public String getOperate110() {
        return this.operate110;
    }
    
    public void setOperate110(String operate110) {
        this.operate110 = operate110;
    }
    


    public java.sql.Timestamp getOperate110Time() {
        return this.operate110Time;
    }
    
    public void setOperate110Time(java.sql.Timestamp operate110Time) {
        this.operate110Time = operate110Time;
    }
    


    public String getOperate117() {
        return this.operate117;
    }
    
    public void setOperate117(String operate117) {
        this.operate117 = operate117;
    }
    


    public java.sql.Timestamp getOperate117Time() {
        return this.operate117Time;
    }
    
    public void setOperate117Time(java.sql.Timestamp operate117Time) {
        this.operate117Time = operate117Time;
    }
    


    public String getOperate121() {
        return this.operate121;
    }
    
    public void setOperate121(String operate121) {
        this.operate121 = operate121;
    }
    


    public java.sql.Timestamp getOperate121Time() {
        return this.operate121Time;
    }
    
    public void setOperate121Time(java.sql.Timestamp operate121Time) {
        this.operate121Time = operate121Time;
    }
    


    public java.sql.Timestamp getOperate203Time() {
        return this.operate203Time;
    }
    
    public void setOperate203Time(java.sql.Timestamp operate203Time) {
        this.operate203Time = operate203Time;
    }
    


    public String getOperate122() {
        return this.operate122;
    }
    
    public void setOperate122(String operate122) {
        this.operate122 = operate122;
    }
    


    public String getOperate125() {
        return this.operate125;
    }
    
    public void setOperate125(String operate125) {
        this.operate125 = operate125;
    }
    


    public java.sql.Timestamp getOperate125Time() {
        return this.operate125Time;
    }
    
    public void setOperate125Time(java.sql.Timestamp operate125Time) {
        this.operate125Time = operate125Time;
    }
    


    public String getOperate126() {
        return this.operate126;
    }
    
    public void setOperate126(String operate126) {
        this.operate126 = operate126;
    }
    


    public java.sql.Timestamp getOperate126Time() {
        return this.operate126Time;
    }
    
    public void setOperate126Time(java.sql.Timestamp operate126Time) {
        this.operate126Time = operate126Time;
    }
    


    public String getOperate127() {
        return this.operate127;
    }
    
    public void setOperate127(String operate127) {
        this.operate127 = operate127;
    }
    


    public java.sql.Timestamp getOperate127Time() {
        return this.operate127Time;
    }
    
    public void setOperate127Time(java.sql.Timestamp operate127Time) {
        this.operate127Time = operate127Time;
    }
    


    public String getOperate201() {
        return this.operate201;
    }
    
    public void setOperate201(String operate201) {
        this.operate201 = operate201;
    }
    


    public java.sql.Timestamp getOperate201Time() {
        return this.operate201Time;
    }
    
    public void setOperate201Time(java.sql.Timestamp operate201Time) {
        this.operate201Time = operate201Time;
    }
    


    public String getOperate202() {
        return this.operate202;
    }
    
    public void setOperate202(String operate202) {
        this.operate202 = operate202;
    }
    


    public java.sql.Timestamp getOperate202Time() {
        return this.operate202Time;
    }
    
    public void setOperate202Time(java.sql.Timestamp operate202Time) {
        this.operate202Time = operate202Time;
    }
    


    public String getOperate203() {
        return this.operate203;
    }
    
    public void setOperate203(String operate203) {
        this.operate203 = operate203;
    }
    


    public java.sql.Timestamp getOperate122Time() {
        return this.operate122Time;
    }
    
    public void setOperate122Time(java.sql.Timestamp operate122Time) {
        this.operate122Time = operate122Time;
    }
    


    public Long getLocked() {
        return this.locked;
    }
    
    public void setLocked(Long locked) {
        this.locked = locked;
    }
    


    public java.sql.Timestamp getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(java.sql.Timestamp createDate) {
        this.createDate = createDate;
    }
    


    public java.util.Set getFlights() {
        return this.flights;
    }
    
    public void setFlights(java.util.Set flights) {
        this.flights = flights;
    }
    


    public java.util.Set getPassengers() {
        return this.passengers;
    }
    
    public void setPassengers(java.util.Set passengers) {
        this.passengers = passengers;
    }
    


    public com.fdays.tsms.transaction.Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(com.fdays.tsms.transaction.Agent agent) {
        this.agent = agent;
    }
    


    public com.fdays.tsms.transaction.Platform getPlatform() {
        return this.platform;
    }
    
    public void setPlatform(com.fdays.tsms.transaction.Platform platform) {
        this.platform = platform;
    }
    


    public com.fdays.tsms.transaction.Company getCompany() {
        return this.company;
    }
    
    public void setCompany(com.fdays.tsms.transaction.Company company) {
        this.company = company;
    }
    


    public com.fdays.tsms.transaction.Account getAccount() {
        return this.account;
    }
    
    public void setAccount(com.fdays.tsms.transaction.Account account) {
        this.account = account;
    }
    


    public com.fdays.tsms.airticket.OrderGroup getOrderGroup() {
        return this.orderGroup;
    }
    
    public void setOrderGroup(com.fdays.tsms.airticket.OrderGroup orderGroup) {
        this.orderGroup = orderGroup;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


