package com.fdays.tsms.airticket._entity;



/**
 * AirlinePlace generated by hbm2java
 */


public class _AirlinePlace 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String code;
     protected Long rate;
     protected String company;
     protected Long status;
     protected com.fdays.tsms.airticket.Airline airline;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    


    public Long getRate() {
        return this.rate;
    }
    
    public void setRate(Long rate) {
        this.rate = rate;
    }
    


    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public com.fdays.tsms.airticket.Airline getAirline() {
        return this.airline;
    }
    
    public void setAirline(com.fdays.tsms.airticket.Airline airline) {
        this.airline = airline;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


