package com.fdays.tsms.airticket._entity;

import com.fdays.tsms.transaction.Statement;



/**
 * AirticketOrder generated by hbm2java
 */


public class _AirticketOrder 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String airOrderNo;
     protected String oldOrderNo;
     
     protected String groupMarkNo;
     protected String drawPnr;
     protected String subPnr;
     protected String bigPnr;
     protected String umbuchenPnr;
     protected java.math.BigDecimal ticketPrice;
     protected java.math.BigDecimal rebate;
     protected Long adultCount;
     protected Long childCount;
     protected Long babyCount;
     protected java.math.BigDecimal airportPrice;
     protected java.math.BigDecimal fuelPrice;
     protected java.math.BigDecimal documentPrice;
     protected java.math.BigDecimal insurancePrice;
     protected java.math.BigDecimal handlingCharge;
     protected String currentOperator;    
     protected String entryOperator;
     protected String payOperator;
     
     protected String drawer;
     protected Long ticketType;
     protected Long tranType;
     protected Long businessType;
     
     protected java.sql.Timestamp entryTime;
     protected java.sql.Timestamp payTime;
     protected java.sql.Timestamp drawTime;     
     protected java.sql.Timestamp optTime;
     
     protected String memo;
     protected Long status;
     protected java.math.BigDecimal totalTicketPrice;
     protected java.math.BigDecimal totalAirportPrice;
     protected java.math.BigDecimal totalFuelPrice;
     protected java.math.BigDecimal proxyPrice;
     protected java.math.BigDecimal incomeretreatCharge;
     protected java.math.BigDecimal overTicketPrice;
     protected java.math.BigDecimal overAirportfulePrice;
     protected java.math.BigDecimal teamaddPrice;
     protected java.math.BigDecimal agentaddPrice;
     protected java.math.BigDecimal commissonCount;
     protected java.math.BigDecimal rakeoffCount;
     protected String returnReason;
     protected java.math.BigDecimal transRule;
     protected java.util.Set flights = new java.util.HashSet(0);
     protected java.util.Set passengers = new java.util.HashSet(0);
     protected com.fdays.tsms.transaction.Statement statement=new Statement();
     protected com.fdays.tsms.transaction.Agent agent;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getAirOrderNo() {
        return this.airOrderNo;
    }
    
    public void setAirOrderNo(String airOrderNo) {
        this.airOrderNo = airOrderNo;
    }
    


    public String getGroupMarkNo() {
        return this.groupMarkNo;
    }
    
    public void setGroupMarkNo(String groupMarkNo) {
        this.groupMarkNo = groupMarkNo;
    }
    
	public String getDrawPnr() {
        return this.drawPnr;
    }
    
    public void setDrawPnr(String drawPnr) {
        this.drawPnr = drawPnr;
    }
    


    public java.sql.Timestamp getDrawTime() {
		return drawTime;
	}

	public void setDrawTime(java.sql.Timestamp drawTime) {
		this.drawTime = drawTime;
	}

	public String getSubPnr() {
        return this.subPnr;
    }
    
    public void setSubPnr(String subPnr) {
        this.subPnr = subPnr;
    }
    


    public String getPayOperator() {
		return payOperator;
	}

	public void setPayOperator(String payOperator) {
		this.payOperator = payOperator;
	}

	public String getBigPnr() {
        return this.bigPnr;
    }
    
    public void setBigPnr(String bigPnr) {
        this.bigPnr = bigPnr;
    }
    


    public String getUmbuchenPnr() {
		return umbuchenPnr;
	}

	public void setUmbuchenPnr(String umbuchenPnr) {
		this.umbuchenPnr = umbuchenPnr;
	}

	public java.math.BigDecimal getTicketPrice() {
        return this.ticketPrice;
    }
    
    public void setTicketPrice(java.math.BigDecimal ticketPrice) {
        this.ticketPrice = ticketPrice;
    }
    


    public java.math.BigDecimal getRebate() {
        return this.rebate;
    }
    
    public void setRebate(java.math.BigDecimal rebate) {
        this.rebate = rebate;
    }
    


    public String getOldOrderNo() {
		return oldOrderNo;
	}

	public void setOldOrderNo(String oldOrderNo) {
		this.oldOrderNo = oldOrderNo;
	}

	public Long getAdultCount() {
        return this.adultCount;
    }
    
    public void setAdultCount(Long adultCount) {
        this.adultCount = adultCount;
    }
    


    public Long getChildCount() {
        return this.childCount;
    }
    
    public void setChildCount(Long childCount) {
        this.childCount = childCount;
    }
    


    public Long getBabyCount() {
        return this.babyCount;
    }
    
    public void setBabyCount(Long babyCount) {
        this.babyCount = babyCount;
    }
    


    public java.math.BigDecimal getAirportPrice() {
        return this.airportPrice;
    }
    
    public void setAirportPrice(java.math.BigDecimal airportPrice) {
        this.airportPrice = airportPrice;
    }
    


    public java.math.BigDecimal getFuelPrice() {
        return this.fuelPrice;
    }
    
    public void setFuelPrice(java.math.BigDecimal fuelPrice) {
        this.fuelPrice = fuelPrice;
    }
    


    public java.math.BigDecimal getDocumentPrice() {
        return this.documentPrice;
    }
    
    public void setDocumentPrice(java.math.BigDecimal documentPrice) {
        this.documentPrice = documentPrice;
    }
    


    public java.math.BigDecimal getInsurancePrice() {
        return this.insurancePrice;
    }
    
    public void setInsurancePrice(java.math.BigDecimal insurancePrice) {
        this.insurancePrice = insurancePrice;
    }
    


    public java.math.BigDecimal getHandlingCharge() {
        return this.handlingCharge;
    }
    
    public void setHandlingCharge(java.math.BigDecimal handlingCharge) {
        this.handlingCharge = handlingCharge;
    }
    


    public String getCurrentOperator() {
        return this.currentOperator;
    }
    
    public void setCurrentOperator(String currentOperator) {
        this.currentOperator = currentOperator;
    }
    


    public String getDrawer() {
        return this.drawer;
    }
    
    public void setDrawer(String drawer) {
        this.drawer = drawer;
    }
    


    public Long getTicketType() {
        return this.ticketType;
    }
    
    public void setTicketType(Long ticketType) {
        this.ticketType = ticketType;
    }
    


    public Long getTranType() {
        return this.tranType;
    }
    
    public void setTranType(Long tranType) {
        this.tranType = tranType;
    }
    


    public Long getBusinessType() {
        return this.businessType;
    }
    
    public void setBusinessType(Long businessType) {
        this.businessType = businessType;
    }
    


    public java.sql.Timestamp getOptTime() {
        return this.optTime;
    }
    
    public void setOptTime(java.sql.Timestamp optTime) {
        this.optTime = optTime;
    }
    


    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public java.math.BigDecimal getTotalTicketPrice() {
        return this.totalTicketPrice;
    }
    
    public void setTotalTicketPrice(java.math.BigDecimal totalTicketPrice) {
        this.totalTicketPrice = totalTicketPrice;
    }
    


    public java.math.BigDecimal getTotalAirportPrice() {
        return this.totalAirportPrice;
    }
    
    public void setTotalAirportPrice(java.math.BigDecimal totalAirportPrice) {
        this.totalAirportPrice = totalAirportPrice;
    }
    


    public java.math.BigDecimal getTotalFuelPrice() {
        return this.totalFuelPrice;
    }
    
    public void setTotalFuelPrice(java.math.BigDecimal totalFuelPrice) {
        this.totalFuelPrice = totalFuelPrice;
    }
    


    public java.math.BigDecimal getProxyPrice() {
        return this.proxyPrice;
    }
    
    public void setProxyPrice(java.math.BigDecimal proxyPrice) {
        this.proxyPrice = proxyPrice;
    }
    


    public java.math.BigDecimal getIncomeretreatCharge() {
        return this.incomeretreatCharge;
    }
    
    public void setIncomeretreatCharge(java.math.BigDecimal incomeretreatCharge) {
        this.incomeretreatCharge = incomeretreatCharge;
    }
    


    public java.math.BigDecimal getOverTicketPrice() {
        return this.overTicketPrice;
    }
    
    public void setOverTicketPrice(java.math.BigDecimal overTicketPrice) {
        this.overTicketPrice = overTicketPrice;
    }
    


    public java.math.BigDecimal getOverAirportfulePrice() {
        return this.overAirportfulePrice;
    }
    
    public void setOverAirportfulePrice(java.math.BigDecimal overAirportfulePrice) {
        this.overAirportfulePrice = overAirportfulePrice;
    }
    


    public java.math.BigDecimal getTeamaddPrice() {
        return this.teamaddPrice;
    }
    
    public void setTeamaddPrice(java.math.BigDecimal teamaddPrice) {
        this.teamaddPrice = teamaddPrice;
    }
    


    public java.math.BigDecimal getAgentaddPrice() {
        return this.agentaddPrice;
    }
    
    public void setAgentaddPrice(java.math.BigDecimal agentaddPrice) {
        this.agentaddPrice = agentaddPrice;
    }
    


    public java.math.BigDecimal getCommissonCount() {
        return this.commissonCount;
    }
    
    public void setCommissonCount(java.math.BigDecimal commissonCount) {
        this.commissonCount = commissonCount;
    }
    


    public java.math.BigDecimal getRakeoffCount() {
        return this.rakeoffCount;
    }
    
    public void setRakeoffCount(java.math.BigDecimal rakeoffCount) {
        this.rakeoffCount = rakeoffCount;
    }
    


    public String getReturnReason() {
        return this.returnReason;
    }
    
    public void setReturnReason(String returnReason) {
        this.returnReason = returnReason;
    }
    


    public java.math.BigDecimal getTransRule() {
        return this.transRule;
    }
    
    public void setTransRule(java.math.BigDecimal transRule) {
        this.transRule = transRule;
    }
    


    public java.util.Set getFlights() {
        return this.flights;
    }
    
    public void setFlights(java.util.Set flights) {
        this.flights = flights;
    }
    


    public java.util.Set getPassengers() {
        return this.passengers;
    }
    
    public void setPassengers(java.util.Set passengers) {
        this.passengers = passengers;
    }
    


    public com.fdays.tsms.transaction.Statement getStatement() {
        return this.statement;
    }
    
    public void setStatement(com.fdays.tsms.transaction.Statement statement) {
        this.statement = statement;
    }
    


    public com.fdays.tsms.transaction.Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(com.fdays.tsms.transaction.Agent agent) {
        this.agent = agent;
    }
    

  // The following is extra code specified in the hbm.xml files

  public String getEntryOperator() {
		return entryOperator;
	}

	public void setEntryOperator(String entryOperator) {
		this.entryOperator = entryOperator;
	}

public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }

public java.sql.Timestamp getEntryTime() {
	return entryTime;
}

public void setEntryTime(java.sql.Timestamp entryTime) {
	this.entryTime = entryTime;
}

public java.sql.Timestamp getPayTime() {
	return payTime;
}

public void setPayTime(java.sql.Timestamp payTime) {
	this.payTime = payTime;
}
 





  // end of extra code specified in the hbm.xml files


}


