package com.fdays.tsms.airticket._entity;



/**
 * StatisticsOrder generated by hbm2java
 */


public class _StatisticsOrder 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String orderNo;
     protected String flightCode;
     protected String startEnd;
     protected String boardingTime;
     protected String passengerName;
     protected String ticketNumber;
     protected java.math.BigDecimal totalAmount;
     protected java.math.BigDecimal profit;
     protected java.math.BigDecimal rate;
     protected java.math.BigDecimal profitAfter;
     protected Long tranType;
     protected Long groupId;
     protected com.fdays.tsms.policy.SaleStatistics saleStatistics;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }
    


    public String getFlightCode() {
        return this.flightCode;
    }
    
    public void setFlightCode(String flightCode) {
        this.flightCode = flightCode;
    }
    


    public String getStartEnd() {
        return this.startEnd;
    }
    
    public void setStartEnd(String startEnd) {
        this.startEnd = startEnd;
    }
    


    public String getBoardingTime() {
        return this.boardingTime;
    }
    
    public void setBoardingTime(String boardingTime) {
        this.boardingTime = boardingTime;
    }
    


    public String getPassengerName() {
        return this.passengerName;
    }
    
    public void setPassengerName(String passengerName) {
        this.passengerName = passengerName;
    }
    


    public String getTicketNumber() {
        return this.ticketNumber;
    }
    
    public void setTicketNumber(String ticketNumber) {
        this.ticketNumber = ticketNumber;
    }
    


    public java.math.BigDecimal getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(java.math.BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }
    


    public java.math.BigDecimal getProfit() {
        return this.profit;
    }
    
    public void setProfit(java.math.BigDecimal profit) {
        this.profit = profit;
    }
    


    public java.math.BigDecimal getRate() {
        return this.rate;
    }
    
    public void setRate(java.math.BigDecimal rate) {
        this.rate = rate;
    }
    


    public java.math.BigDecimal getProfitAfter() {
        return this.profitAfter;
    }
    
    public void setProfitAfter(java.math.BigDecimal profitAfter) {
        this.profitAfter = profitAfter;
    }
    


    public Long getTranType() {
        return this.tranType;
    }
    
    public void setTranType(Long tranType) {
        this.tranType = tranType;
    }
    


    public Long getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }
    


    public com.fdays.tsms.policy.SaleStatistics getSaleStatistics() {
        return this.saleStatistics;
    }
    
    public void setSaleStatistics(com.fdays.tsms.policy.SaleStatistics saleStatistics) {
        this.saleStatistics = saleStatistics;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


