package com.fdays.tsms.transaction._entity;



/**
 * Account generated by hbm2java
 */


public class _Account 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String name;
     protected String accountNo;
     protected Long tranType;
     protected Long type;
     protected String description;
     protected Long status;
     protected java.util.Set airticketOrders = new java.util.HashSet(0);
     protected com.fdays.tsms.transaction.PaymentTool paymentTool;
     protected java.util.Set platComAccounts = new java.util.HashSet(0);
     protected java.util.Set accountChecks = new java.util.HashSet(0);

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    


    public String getAccountNo() {
        return this.accountNo;
    }
    
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }
    


    public Long getTranType() {
        return this.tranType;
    }
    
    public void setTranType(Long tranType) {
        this.tranType = tranType;
    }
    


    public Long getType() {
        return this.type;
    }
    
    public void setType(Long type) {
        this.type = type;
    }
    


    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public java.util.Set getAirticketOrders() {
        return this.airticketOrders;
    }
    
    public void setAirticketOrders(java.util.Set airticketOrders) {
        this.airticketOrders = airticketOrders;
    }
    


    public com.fdays.tsms.transaction.PaymentTool getPaymentTool() {
        return this.paymentTool;
    }
    
    public void setPaymentTool(com.fdays.tsms.transaction.PaymentTool paymentTool) {
        this.paymentTool = paymentTool;
    }
    


    public java.util.Set getPlatComAccounts() {
        return this.platComAccounts;
    }
    
    public void setPlatComAccounts(java.util.Set platComAccounts) {
        this.platComAccounts = platComAccounts;
    }
    


    public java.util.Set getAccountChecks() {
        return this.accountChecks;
    }
    
    public void setAccountChecks(java.util.Set accountChecks) {
        this.accountChecks = accountChecks;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


