package com.fdays.tsms.transaction._entity;



/**
 * Agent generated by hbm2java
 */


public class _Agent 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String name;
     protected String contactWay;
     protected String address;
     protected Long type;
     protected String memo;
     protected Long status;
     protected String userName;
     protected java.sql.Timestamp updateDate;
     protected java.util.Set airticketOrders = new java.util.HashSet(0);
     protected com.fdays.tsms.transaction.Company company;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    


    public String getContactWay() {
        return this.contactWay;
    }
    
    public void setContactWay(String contactWay) {
        this.contactWay = contactWay;
    }
    


    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    


    public Long getType() {
        return this.type;
    }
    
    public void setType(Long type) {
        this.type = type;
    }
    


    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    


    public java.sql.Timestamp getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(java.sql.Timestamp updateDate) {
        this.updateDate = updateDate;
    }
    


    public java.util.Set getAirticketOrders() {
        return this.airticketOrders;
    }
    
    public void setAirticketOrders(java.util.Set airticketOrders) {
        this.airticketOrders = airticketOrders;
    }
    


    public com.fdays.tsms.transaction.Company getCompany() {
        return this.company;
    }
    
    public void setCompany(com.fdays.tsms.transaction.Company company) {
        this.company = company;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


