package com.fdays.tsms.transaction._entity;



/**
 * BankCardPayment generated by hbm2java
 */


public class _BankCardPayment 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String userName;
     protected java.math.BigDecimal account1;
     protected java.math.BigDecimal account2;
     protected java.math.BigDecimal account3;
     protected java.math.BigDecimal subtotal;
     protected java.math.BigDecimal total;
     protected java.sql.Timestamp banlanceDate;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    


    public java.math.BigDecimal getAccount1() {
        return this.account1;
    }
    
    public void setAccount1(java.math.BigDecimal account1) {
        this.account1 = account1;
    }
    


    public java.math.BigDecimal getAccount2() {
        return this.account2;
    }
    
    public void setAccount2(java.math.BigDecimal account2) {
        this.account2 = account2;
    }
    


    public java.math.BigDecimal getAccount3() {
        return this.account3;
    }
    
    public void setAccount3(java.math.BigDecimal account3) {
        this.account3 = account3;
    }
    


    public java.math.BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(java.math.BigDecimal subtotal) {
        this.subtotal = subtotal;
    }
    


    public java.math.BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(java.math.BigDecimal total) {
        this.total = total;
    }
    


    public java.sql.Timestamp getBanlanceDate() {
        return this.banlanceDate;
    }
    
    public void setBanlanceDate(java.sql.Timestamp banlanceDate) {
        this.banlanceDate = banlanceDate;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


