package com.fdays.tsms.transaction._entity;



/**
 * PlatComAccount generated by hbm2java
 */


public class _PlatComAccount 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected Long type;
     protected String description;
     protected Long status;
     protected com.fdays.tsms.transaction.Platform platform;
     protected com.fdays.tsms.transaction.Company company;
     protected com.fdays.tsms.transaction.Account account;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public Long getType() {
        return this.type;
    }
    
    public void setType(Long type) {
        this.type = type;
    }
    


    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public com.fdays.tsms.transaction.Platform getPlatform() {
        return this.platform;
    }
    
    public void setPlatform(com.fdays.tsms.transaction.Platform platform) {
        this.platform = platform;
    }
    


    public com.fdays.tsms.transaction.Company getCompany() {
        return this.company;
    }
    
    public void setCompany(com.fdays.tsms.transaction.Company company) {
        this.company = company;
    }
    


    public com.fdays.tsms.transaction.Account getAccount() {
        return this.account;
    }
    
    public void setAccount(com.fdays.tsms.transaction.Account account) {
        this.account = account;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


