package com.fdays.tsms.transaction._entity;



/**
 * PlatformReportIndex generated by hbm2java
 */


public class _PlatformReportIndex 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected Long platformId;
     protected Long flightCode;
     protected Long flightClass;
     protected Long ticketNumber;
     protected Long startPoint;
     protected Long endPoint;
     protected Long subPnr;
     protected Long discount;
     protected String memo;
     protected Long type;
     protected Long status;
     protected java.sql.Timestamp lastDate;
     protected String userNo;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public Long getPlatformId() {
        return this.platformId;
    }
    
    public void setPlatformId(Long platformId) {
        this.platformId = platformId;
    }
    


    public Long getFlightCode() {
        return this.flightCode;
    }
    
    public void setFlightCode(Long flightCode) {
        this.flightCode = flightCode;
    }
    


    public Long getFlightClass() {
        return this.flightClass;
    }
    
    public void setFlightClass(Long flightClass) {
        this.flightClass = flightClass;
    }
    


    public Long getTicketNumber() {
        return this.ticketNumber;
    }
    
    public void setTicketNumber(Long ticketNumber) {
        this.ticketNumber = ticketNumber;
    }
    


    public Long getStartPoint() {
        return this.startPoint;
    }
    
    public void setStartPoint(Long startPoint) {
        this.startPoint = startPoint;
    }
    


    public Long getEndPoint() {
        return this.endPoint;
    }
    
    public void setEndPoint(Long endPoint) {
        this.endPoint = endPoint;
    }
    


    public Long getSubPnr() {
        return this.subPnr;
    }
    
    public void setSubPnr(Long subPnr) {
        this.subPnr = subPnr;
    }
    


    public Long getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Long discount) {
        this.discount = discount;
    }
    


    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }
    


    public Long getType() {
        return this.type;
    }
    
    public void setType(Long type) {
        this.type = type;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public java.sql.Timestamp getLastDate() {
        return this.lastDate;
    }
    
    public void setLastDate(java.sql.Timestamp lastDate) {
        this.lastDate = lastDate;
    }
    


    public String getUserNo() {
        return this.userNo;
    }
    
    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


