package com.fdays.tsms.transaction._entity;



/**
 * ReportCompareResult generated by hbm2java
 */


public class _ReportCompareResult 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String name;
     protected Long paymenttoolId;
     protected Long accountId;
     protected Long platformId;
     protected java.sql.Timestamp beginDate;
     protected java.sql.Timestamp endDate;
     protected String memo;
     protected String userNo;
     protected java.sql.Timestamp lastDate;
     protected Long compareType;
     protected Long tranType;
     protected Long type;
     protected Long status;
     protected java.util.Set reportRecodes = new java.util.HashSet(0);

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    


    public Long getPaymenttoolId() {
        return this.paymenttoolId;
    }
    
    public void setPaymenttoolId(Long paymenttoolId) {
        this.paymenttoolId = paymenttoolId;
    }
    


    public Long getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }
    


    public Long getPlatformId() {
        return this.platformId;
    }
    
    public void setPlatformId(Long platformId) {
        this.platformId = platformId;
    }
    


    public java.sql.Timestamp getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(java.sql.Timestamp beginDate) {
        this.beginDate = beginDate;
    }
    


    public java.sql.Timestamp getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(java.sql.Timestamp endDate) {
        this.endDate = endDate;
    }
    


    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }
    


    public String getUserNo() {
        return this.userNo;
    }
    
    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }
    


    public java.sql.Timestamp getLastDate() {
        return this.lastDate;
    }
    
    public void setLastDate(java.sql.Timestamp lastDate) {
        this.lastDate = lastDate;
    }
    


    public Long getCompareType() {
        return this.compareType;
    }
    
    public void setCompareType(Long compareType) {
        this.compareType = compareType;
    }
    


    public Long getTranType() {
        return this.tranType;
    }
    
    public void setTranType(Long tranType) {
        this.tranType = tranType;
    }
    


    public Long getType() {
        return this.type;
    }
    
    public void setType(Long type) {
        this.type = type;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public java.util.Set getReportRecodes() {
        return this.reportRecodes;
    }
    
    public void setReportRecodes(java.util.Set reportRecodes) {
        this.reportRecodes = reportRecodes;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


