package com.fdays.tsms.transaction._entity;



/**
 * ReportRecode generated by hbm2java
 */


public class _ReportRecode 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected Long payToolId;
     protected Long platformId;
     protected String subPnr;
     protected String airOrderNo;
     protected Long statementType;
     protected java.math.BigDecimal amount;
     protected Long accountId;
     protected String accountName;
     protected Long passengerCount;
     protected java.sql.Timestamp reportDate;
     protected String reportName;
     protected Long reportRownum;
     protected Long status;
     protected Long type;
     protected String memo;
     protected com.fdays.tsms.transaction.ReportRecodeResult reportRecodeResult;
     protected com.fdays.tsms.transaction.ReportCompareResult reportCompareResult;
     protected com.fdays.tsms.transaction.PlatformReportIndex platformReportIndex;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public Long getPayToolId() {
        return this.payToolId;
    }
    
    public void setPayToolId(Long payToolId) {
        this.payToolId = payToolId;
    }
    


    public Long getPlatformId() {
        return this.platformId;
    }
    
    public void setPlatformId(Long platformId) {
        this.platformId = platformId;
    }
    


    public String getSubPnr() {
        return this.subPnr;
    }
    
    public void setSubPnr(String subPnr) {
        this.subPnr = subPnr;
    }
    


    public String getAirOrderNo() {
        return this.airOrderNo;
    }
    
    public void setAirOrderNo(String airOrderNo) {
        this.airOrderNo = airOrderNo;
    }
    


    public Long getStatementType() {
        return this.statementType;
    }
    
    public void setStatementType(Long statementType) {
        this.statementType = statementType;
    }
    


    public java.math.BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(java.math.BigDecimal amount) {
        this.amount = amount;
    }
    


    public Long getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }
    


    public String getAccountName() {
        return this.accountName;
    }
    
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }
    


    public Long getPassengerCount() {
        return this.passengerCount;
    }
    
    public void setPassengerCount(Long passengerCount) {
        this.passengerCount = passengerCount;
    }
    


    public java.sql.Timestamp getReportDate() {
        return this.reportDate;
    }
    
    public void setReportDate(java.sql.Timestamp reportDate) {
        this.reportDate = reportDate;
    }
    


    public String getReportName() {
        return this.reportName;
    }
    
    public void setReportName(String reportName) {
        this.reportName = reportName;
    }
    


    public Long getReportRownum() {
        return this.reportRownum;
    }
    
    public void setReportRownum(Long reportRownum) {
        this.reportRownum = reportRownum;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public Long getType() {
        return this.type;
    }
    
    public void setType(Long type) {
        this.type = type;
    }
    


    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }
    


    public com.fdays.tsms.transaction.ReportRecodeResult getReportRecodeResult() {
        return this.reportRecodeResult;
    }
    
    public void setReportRecodeResult(com.fdays.tsms.transaction.ReportRecodeResult reportRecodeResult) {
        this.reportRecodeResult = reportRecodeResult;
    }
    


    public com.fdays.tsms.transaction.ReportCompareResult getReportCompareResult() {
        return this.reportCompareResult;
    }
    
    public void setReportCompareResult(com.fdays.tsms.transaction.ReportCompareResult reportCompareResult) {
        this.reportCompareResult = reportCompareResult;
    }
    


    public com.fdays.tsms.transaction.PlatformReportIndex getPlatformReportIndex() {
        return this.platformReportIndex;
    }
    
    public void setPlatformReportIndex(com.fdays.tsms.transaction.PlatformReportIndex platformReportIndex) {
        this.platformReportIndex = platformReportIndex;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


