package com.fdays.tsms.transaction._entity;



/**
 * ReportCompare generated by hbm2java
 */


public class _ReportCompare 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected Long reportRownum;
     protected Long orderId;
     protected String subPnr;
     protected String airOrderNo;
     protected java.math.BigDecimal totalAirportfuelPrice;
     protected java.math.BigDecimal ticketPrice;
     protected java.math.BigDecimal inAmount;
     protected java.math.BigDecimal outAmount;
     protected java.math.BigDecimal inRetireAmount;
     protected java.math.BigDecimal outRetireAmount;
     protected Long passengerCount;
     protected String flightCode;
     protected String flightClass;
     protected String ticketNumber;
     protected String startPoint;
     protected String endPoint;
     protected String inAccountName;
     protected String outAccountName;
     protected String outRetireAccountName;
     protected String inRetireAccountName;
     protected Long status;
     protected Long type;
     protected String memo;
     protected String inAccountNo;
     protected String outAccountNo;
     protected String outRetireAccountNo;
     protected String inRetireAccountNo;
     protected com.fdays.tsms.transaction.ReportCompareResult reportCompareResult;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public Long getReportRownum() {
        return this.reportRownum;
    }
    
    public void setReportRownum(Long reportRownum) {
        this.reportRownum = reportRownum;
    }
    


    public Long getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }
    


    public String getSubPnr() {
        return this.subPnr;
    }
    
    public void setSubPnr(String subPnr) {
        this.subPnr = subPnr;
    }
    


    public String getAirOrderNo() {
        return this.airOrderNo;
    }
    
    public void setAirOrderNo(String airOrderNo) {
        this.airOrderNo = airOrderNo;
    }
    


    public java.math.BigDecimal getTotalAirportfuelPrice() {
        return this.totalAirportfuelPrice;
    }
    
    public void setTotalAirportfuelPrice(java.math.BigDecimal totalAirportfuelPrice) {
        this.totalAirportfuelPrice = totalAirportfuelPrice;
    }
    


    public java.math.BigDecimal getTicketPrice() {
        return this.ticketPrice;
    }
    
    public void setTicketPrice(java.math.BigDecimal ticketPrice) {
        this.ticketPrice = ticketPrice;
    }
    


    public java.math.BigDecimal getInAmount() {
        return this.inAmount;
    }
    
    public void setInAmount(java.math.BigDecimal inAmount) {
        this.inAmount = inAmount;
    }
    


    public java.math.BigDecimal getOutAmount() {
        return this.outAmount;
    }
    
    public void setOutAmount(java.math.BigDecimal outAmount) {
        this.outAmount = outAmount;
    }
    


    public java.math.BigDecimal getInRetireAmount() {
        return this.inRetireAmount;
    }
    
    public void setInRetireAmount(java.math.BigDecimal inRetireAmount) {
        this.inRetireAmount = inRetireAmount;
    }
    


    public java.math.BigDecimal getOutRetireAmount() {
        return this.outRetireAmount;
    }
    
    public void setOutRetireAmount(java.math.BigDecimal outRetireAmount) {
        this.outRetireAmount = outRetireAmount;
    }
    


    public Long getPassengerCount() {
        return this.passengerCount;
    }
    
    public void setPassengerCount(Long passengerCount) {
        this.passengerCount = passengerCount;
    }
    


    public String getFlightCode() {
        return this.flightCode;
    }
    
    public void setFlightCode(String flightCode) {
        this.flightCode = flightCode;
    }
    


    public String getFlightClass() {
        return this.flightClass;
    }
    
    public void setFlightClass(String flightClass) {
        this.flightClass = flightClass;
    }
    


    public String getTicketNumber() {
        return this.ticketNumber;
    }
    
    public void setTicketNumber(String ticketNumber) {
        this.ticketNumber = ticketNumber;
    }
    


    public String getStartPoint() {
        return this.startPoint;
    }
    
    public void setStartPoint(String startPoint) {
        this.startPoint = startPoint;
    }
    


    public String getEndPoint() {
        return this.endPoint;
    }
    
    public void setEndPoint(String endPoint) {
        this.endPoint = endPoint;
    }
    


    public String getInAccountName() {
        return this.inAccountName;
    }
    
    public void setInAccountName(String inAccountName) {
        this.inAccountName = inAccountName;
    }
    


    public String getOutAccountName() {
        return this.outAccountName;
    }
    
    public void setOutAccountName(String outAccountName) {
        this.outAccountName = outAccountName;
    }
    


    public String getOutRetireAccountName() {
        return this.outRetireAccountName;
    }
    
    public void setOutRetireAccountName(String outRetireAccountName) {
        this.outRetireAccountName = outRetireAccountName;
    }
    


    public String getInRetireAccountName() {
        return this.inRetireAccountName;
    }
    
    public void setInRetireAccountName(String inRetireAccountName) {
        this.inRetireAccountName = inRetireAccountName;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public Long getType() {
        return this.type;
    }
    
    public void setType(Long type) {
        this.type = type;
    }
    


    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }
    


    public String getInAccountNo() {
        return this.inAccountNo;
    }
    
    public void setInAccountNo(String inAccountNo) {
        this.inAccountNo = inAccountNo;
    }
    


    public String getOutAccountNo() {
        return this.outAccountNo;
    }
    
    public void setOutAccountNo(String outAccountNo) {
        this.outAccountNo = outAccountNo;
    }
    


    public String getOutRetireAccountNo() {
        return this.outRetireAccountNo;
    }
    
    public void setOutRetireAccountNo(String outRetireAccountNo) {
        this.outRetireAccountNo = outRetireAccountNo;
    }
    


    public String getInRetireAccountNo() {
        return this.inRetireAccountNo;
    }
    
    public void setInRetireAccountNo(String inRetireAccountNo) {
        this.inRetireAccountNo = inRetireAccountNo;
    }
    


    public com.fdays.tsms.transaction.ReportCompareResult getReportCompareResult() {
        return this.reportCompareResult;
    }
    
    public void setReportCompareResult(com.fdays.tsms.transaction.ReportCompareResult reportCompareResult) {
        this.reportCompareResult = reportCompareResult;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


