package com.fdays.tsms.transaction._entity;



/**
 * Statement generated by hbm2java
 */


public class _Statement 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String statementNo;
     protected Long orderId;
     protected Long orderType;
     protected Long fromAccountId;
     protected Long toAccountId;
     protected java.math.BigDecimal totalAmount;
     protected java.sql.Timestamp optTime;
     protected Long type;
     protected Long status;
     protected java.sql.Timestamp statementDate;
     protected com.fdays.tsms.user.SysUser sysUser;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getStatementNo() {
        return this.statementNo;
    }
    
    public void setStatementNo(String statementNo) {
        this.statementNo = statementNo;
    }
    


    public Long getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }
    


    public Long getOrderType() {
        return this.orderType;
    }
    
    public void setOrderType(Long orderType) {
        this.orderType = orderType;
    }
    


    public Long getFromAccountId() {
        return this.fromAccountId;
    }
    
    public void setFromAccountId(Long fromAccountId) {
        this.fromAccountId = fromAccountId;
    }
    


    public Long getToAccountId() {
        return this.toAccountId;
    }
    
    public void setToAccountId(Long toAccountId) {
        this.toAccountId = toAccountId;
    }
    


    public java.math.BigDecimal getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(java.math.BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }
    


    public java.sql.Timestamp getOptTime() {
        return this.optTime;
    }
    
    public void setOptTime(java.sql.Timestamp optTime) {
        this.optTime = optTime;
    }
    


    public Long getType() {
        return this.type;
    }
    
    public void setType(Long type) {
        this.type = type;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public java.sql.Timestamp getStatementDate() {
        return this.statementDate;
    }
    
    public void setStatementDate(java.sql.Timestamp statementDate) {
        this.statementDate = statementDate;
    }
    


    public com.fdays.tsms.user.SysUser getSysUser() {
        return this.sysUser;
    }
    
    public void setSysUser(com.fdays.tsms.user.SysUser sysUser) {
        this.sysUser = sysUser;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


