package com.fdays.tsms.transaction._entity;

import java.math.BigDecimal;



/**
 * Statement generated by hbm2java
 */


public class _Statement 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String statementNo;
     protected Long fromAccountId;
     protected Long toAccountId;
     protected Long orderType;
     protected java.math.BigDecimal totalAmount=new  BigDecimal(0);
     protected java.math.BigDecimal actualAmount;
     protected java.math.BigDecimal unsettledAccount;
     protected java.math.BigDecimal commission;
     protected java.math.BigDecimal rakeOff;
     protected java.sql.Timestamp optTime;
     protected Long type;
     protected Long status;
     protected java.util.Set airticketOrders = new java.util.HashSet(0);
     protected com.fdays.tsms.user.SysUser sysUser;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getStatementNo() {
        return this.statementNo;
    }
    
    public void setStatementNo(String statementNo) {
        this.statementNo = statementNo;
    }
    


    public Long getFromAccountId() {
        return this.fromAccountId;
    }
    
    public void setFromAccountId(Long fromAccountId) {
        this.fromAccountId = fromAccountId;
    }
    


    public Long getToAccountId() {
        return this.toAccountId;
    }
    
    public void setToAccountId(Long toAccountId) {
        this.toAccountId = toAccountId;
    }
    


    public Long getOrderType() {
        return this.orderType;
    }
    
    public void setOrderType(Long orderType) {
        this.orderType = orderType;
    }
    


    public java.math.BigDecimal getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(java.math.BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }
    


    public java.math.BigDecimal getActualAmount() {
        return this.actualAmount;
    }
    
    public void setActualAmount(java.math.BigDecimal actualAmount) {
        this.actualAmount = actualAmount;
    }
    


    public java.math.BigDecimal getUnsettledAccount() {
        return this.unsettledAccount;
    }
    
    public void setUnsettledAccount(java.math.BigDecimal unsettledAccount) {
        this.unsettledAccount = unsettledAccount;
    }
    


    public java.math.BigDecimal getCommission() {
        return this.commission;
    }
    
    public void setCommission(java.math.BigDecimal commission) {
        this.commission = commission;
    }
    


    public java.math.BigDecimal getRakeOff() {
        return this.rakeOff;
    }
    
    public void setRakeOff(java.math.BigDecimal rakeOff) {
        this.rakeOff = rakeOff;
    }
    


    public java.sql.Timestamp getOptTime() {
        return this.optTime;
    }
    
    public void setOptTime(java.sql.Timestamp optTime) {
        this.optTime = optTime;
    }
    


    public Long getType() {
        return this.type;
    }
    
    public void setType(Long type) {
        this.type = type;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public java.util.Set getAirticketOrders() {
        return this.airticketOrders;
    }
    
    public void setAirticketOrders(java.util.Set airticketOrders) {
        this.airticketOrders = airticketOrders;
    }
    


    public com.fdays.tsms.user.SysUser getSysUser() {
        return this.sysUser;
    }
    
    public void setSysUser(com.fdays.tsms.user.SysUser sysUser) {
        this.sysUser = sysUser;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


