package com.fdays.tsms.airticket._entity;



/**
 * Flight generated by hbm2java
 */


public class _Flight 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String flightCode;
     protected String startPoint;
     protected String endPoint;
     protected java.sql.Timestamp boardingTime;
     protected String flightClass;
     protected String discount;
     protected Long status;
     protected com.fdays.tsms.airticket.AirticketOrder airticketOrder;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getFlightCode() {
        return this.flightCode;
    }
    
    public void setFlightCode(String flightCode) {
        this.flightCode = flightCode;
    }
    


    public String getStartPoint() {
        return this.startPoint;
    }
    
    public void setStartPoint(String startPoint) {
        this.startPoint = startPoint;
    }
    


    public String getEndPoint() {
        return this.endPoint;
    }
    
    public void setEndPoint(String endPoint) {
        this.endPoint = endPoint;
    }
    


    public java.sql.Timestamp getBoardingTime() {
        return this.boardingTime;
    }
    
    public void setBoardingTime(java.sql.Timestamp boardingTime) {
        this.boardingTime = boardingTime;
    }
    


    public String getFlightClass() {
        return this.flightClass;
    }
    
    public void setFlightClass(String flightClass) {
        this.flightClass = flightClass;
    }
    


    public String getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(String discount) {
        this.discount = discount;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public com.fdays.tsms.airticket.AirticketOrder getAirticketOrder() {
        return this.airticketOrder;
    }
    
    public void setAirticketOrder(com.fdays.tsms.airticket.AirticketOrder airticketOrder) {
        this.airticketOrder = airticketOrder;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


