package com.fdays.tsms.policy._entity;



/**
 * PolicyAfter generated by hbm2java
 */


public class _PolicyAfter 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String flightCode;
     protected String flightCodeExcept;
     protected String startEnd;
     protected String flightClass;
     protected String flightClassExcept;
     protected Long discount;
     protected java.math.BigDecimal rate;
     protected Long travelType;
     protected Long ticketType;
     protected java.math.BigDecimal quota;
     protected String memo;
     protected String userName;
     protected java.sql.Timestamp updateDate;
     protected Long status;
     protected com.fdays.tsms.policy.AirlinePolicyAfter airlinePolicyAfter;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getFlightCode() {
        return this.flightCode;
    }
    
    public void setFlightCode(String flightCode) {
        this.flightCode = flightCode;
    }
    


    public String getFlightCodeExcept() {
        return this.flightCodeExcept;
    }
    
    public void setFlightCodeExcept(String flightCodeExcept) {
        this.flightCodeExcept = flightCodeExcept;
    }
    


    public String getStartEnd() {
        return this.startEnd;
    }
    
    public void setStartEnd(String startEnd) {
        this.startEnd = startEnd;
    }
    


    public String getFlightClass() {
        return this.flightClass;
    }
    
    public void setFlightClass(String flightClass) {
        this.flightClass = flightClass;
    }
    


    public String getFlightClassExcept() {
        return this.flightClassExcept;
    }
    
    public void setFlightClassExcept(String flightClassExcept) {
        this.flightClassExcept = flightClassExcept;
    }
    


    public Long getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Long discount) {
        this.discount = discount;
    }
    


    public java.math.BigDecimal getRate() {
        return this.rate;
    }
    
    public void setRate(java.math.BigDecimal rate) {
        this.rate = rate;
    }
    


    public Long getTravelType() {
        return this.travelType;
    }
    
    public void setTravelType(Long travelType) {
        this.travelType = travelType;
    }
    


    public Long getTicketType() {
        return this.ticketType;
    }
    
    public void setTicketType(Long ticketType) {
        this.ticketType = ticketType;
    }
    


    public java.math.BigDecimal getQuota() {
        return this.quota;
    }
    
    public void setQuota(java.math.BigDecimal quota) {
        this.quota = quota;
    }
    


    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }
    


    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    


    public java.sql.Timestamp getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(java.sql.Timestamp updateDate) {
        this.updateDate = updateDate;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public com.fdays.tsms.policy.AirlinePolicyAfter getAirlinePolicyAfter() {
        return this.airlinePolicyAfter;
    }
    
    public void setAirlinePolicyAfter(com.fdays.tsms.policy.AirlinePolicyAfter airlinePolicyAfter) {
        this.airlinePolicyAfter = airlinePolicyAfter;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


