package com.fdays.tsms.policy._entity;



/**
 * SaleStatistics generated by hbm2java
 */


public class _SaleStatistics 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String carrier;
     protected java.sql.Timestamp beginDate;
     protected java.sql.Timestamp endDate;
     protected Long ticketNum;
     protected Long highClassTicketNum;
     protected java.math.BigDecimal highClassAward;
     protected java.math.BigDecimal saleAmount;
     protected java.math.BigDecimal profitAfter;
     protected java.math.BigDecimal profit;
     protected Long status;
     protected java.math.BigDecimal afterAmount;
     protected java.util.Set statisticsOrders = new java.util.HashSet(0);
     protected com.fdays.tsms.policy.AirlinePolicyAfter airlinePolicyAfter;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getCarrier() {
        return this.carrier;
    }
    
    public void setCarrier(String carrier) {
        this.carrier = carrier;
    }
    


    public java.sql.Timestamp getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(java.sql.Timestamp beginDate) {
        this.beginDate = beginDate;
    }
    


    public java.sql.Timestamp getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(java.sql.Timestamp endDate) {
        this.endDate = endDate;
    }
    


    public Long getTicketNum() {
        return this.ticketNum;
    }
    
    public void setTicketNum(Long ticketNum) {
        this.ticketNum = ticketNum;
    }
    


    public Long getHighClassTicketNum() {
        return this.highClassTicketNum;
    }
    
    public void setHighClassTicketNum(Long highClassTicketNum) {
        this.highClassTicketNum = highClassTicketNum;
    }
    


    public java.math.BigDecimal getHighClassAward() {
        return this.highClassAward;
    }
    
    public void setHighClassAward(java.math.BigDecimal highClassAward) {
        this.highClassAward = highClassAward;
    }
    


    public java.math.BigDecimal getSaleAmount() {
        return this.saleAmount;
    }
    
    public void setSaleAmount(java.math.BigDecimal saleAmount) {
        this.saleAmount = saleAmount;
    }
    


    public java.math.BigDecimal getProfitAfter() {
        return this.profitAfter;
    }
    
    public void setProfitAfter(java.math.BigDecimal profitAfter) {
        this.profitAfter = profitAfter;
    }
    


    public java.math.BigDecimal getProfit() {
        return this.profit;
    }
    
    public void setProfit(java.math.BigDecimal profit) {
        this.profit = profit;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public java.math.BigDecimal getAfterAmount() {
        return this.afterAmount;
    }
    
    public void setAfterAmount(java.math.BigDecimal afterAmount) {
        this.afterAmount = afterAmount;
    }
    


    public java.util.Set getStatisticsOrders() {
        return this.statisticsOrders;
    }
    
    public void setStatisticsOrders(java.util.Set statisticsOrders) {
        this.statisticsOrders = statisticsOrders;
    }
    


    public com.fdays.tsms.policy.AirlinePolicyAfter getAirlinePolicyAfter() {
        return this.airlinePolicyAfter;
    }
    
    public void setAirlinePolicyAfter(com.fdays.tsms.policy.AirlinePolicyAfter airlinePolicyAfter) {
        this.airlinePolicyAfter = airlinePolicyAfter;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


