package com.fdays.tsms.transaction._entity;



/**
 * PlatformbankCardPayment generated by hbm2java
 */


public class _PlatformbankCardPayment 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String platform;
     protected java.math.BigDecimal fromAccount1;
     protected java.math.BigDecimal toAccount1;
     protected java.math.BigDecimal fromAccount2;
     protected java.math.BigDecimal toAccount2;
     protected java.math.BigDecimal fromAccount3;
     protected java.math.BigDecimal toAccount3;
     protected java.math.BigDecimal fromAccount4;
     protected java.math.BigDecimal toAccount4;
     protected java.sql.Timestamp banlanceDate;
     protected java.math.BigDecimal allToAccount;
     protected java.math.BigDecimal allFromAccount;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getPlatform() {
        return this.platform;
    }
    
    public void setPlatform(String platform) {
        this.platform = platform;
    }
    


    public java.math.BigDecimal getFromAccount1() {
        return this.fromAccount1;
    }
    
    public void setFromAccount1(java.math.BigDecimal fromAccount1) {
        this.fromAccount1 = fromAccount1;
    }
    


    public java.math.BigDecimal getToAccount1() {
        return this.toAccount1;
    }
    
    public void setToAccount1(java.math.BigDecimal toAccount1) {
        this.toAccount1 = toAccount1;
    }
    


    public java.math.BigDecimal getFromAccount2() {
        return this.fromAccount2;
    }
    
    public void setFromAccount2(java.math.BigDecimal fromAccount2) {
        this.fromAccount2 = fromAccount2;
    }
    


    public java.math.BigDecimal getToAccount2() {
        return this.toAccount2;
    }
    
    public void setToAccount2(java.math.BigDecimal toAccount2) {
        this.toAccount2 = toAccount2;
    }
    


    public java.math.BigDecimal getFromAccount3() {
        return this.fromAccount3;
    }
    
    public void setFromAccount3(java.math.BigDecimal fromAccount3) {
        this.fromAccount3 = fromAccount3;
    }
    


    public java.math.BigDecimal getToAccount3() {
        return this.toAccount3;
    }
    
    public void setToAccount3(java.math.BigDecimal toAccount3) {
        this.toAccount3 = toAccount3;
    }
    


    public java.math.BigDecimal getFromAccount4() {
        return this.fromAccount4;
    }
    
    public void setFromAccount4(java.math.BigDecimal fromAccount4) {
        this.fromAccount4 = fromAccount4;
    }
    


    public java.math.BigDecimal getToAccount4() {
        return this.toAccount4;
    }
    
    public void setToAccount4(java.math.BigDecimal toAccount4) {
        this.toAccount4 = toAccount4;
    }
    


    public java.sql.Timestamp getBanlanceDate() {
        return this.banlanceDate;
    }
    
    public void setBanlanceDate(java.sql.Timestamp banlanceDate) {
        this.banlanceDate = banlanceDate;
    }
    


    public java.math.BigDecimal getAllToAccount() {
        return this.allToAccount;
    }
    
    public void setAllToAccount(java.math.BigDecimal allToAccount) {
        this.allToAccount = allToAccount;
    }
    


    public java.math.BigDecimal getAllFromAccount() {
        return this.allFromAccount;
    }
    
    public void setAllFromAccount(java.math.BigDecimal allFromAccount) {
        this.allFromAccount = allFromAccount;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


