package com.fdays.tsms.system._entity;



/**
 * TicketLog generated by hbm2java
 */


public class _TicketLog 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected Long orderId;
     protected String orderNo;
     protected Long orderType;
     protected String ip;
     protected java.sql.Timestamp optTime;
     protected Long type;
     protected String content;
     protected Long status;
     protected com.fdays.tsms.user.SysUser sysUser;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public Long getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }
    


    public String getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }
    


    public Long getOrderType() {
        return this.orderType;
    }
    
    public void setOrderType(Long orderType) {
        this.orderType = orderType;
    }
    


    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    


    public java.sql.Timestamp getOptTime() {
        return this.optTime;
    }
    
    public void setOptTime(java.sql.Timestamp optTime) {
        this.optTime = optTime;
    }
    


    public Long getType() {
        return this.type;
    }
    
    public void setType(Long type) {
        this.type = type;
    }
    


    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public com.fdays.tsms.user.SysUser getSysUser() {
        return this.sysUser;
    }
    
    public void setSysUser(com.fdays.tsms.user.SysUser sysUser) {
        this.sysUser = sysUser;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


