package com.fdays.tsms.transaction._entity;



/**
 * OptTransaction generated by hbm2java
 */


public class _OptTransaction 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String userName;
     protected Long sellorderstotal;
     protected Long normalorder;
     protected Long alteredorder;
     protected Long refundorder;
     protected Long invalidorder;
     protected Long cancelorder;
     protected Long soldticketCount;
     protected java.math.BigDecimal inamount;
     protected java.math.BigDecimal outamount;
     protected java.math.BigDecimal profit;
     protected java.math.BigDecimal refundamountreceived;
     protected java.math.BigDecimal refundamountpaid;
     protected java.math.BigDecimal cancelticketcollection;
     protected java.math.BigDecimal cancelticketrefund;
     protected java.sql.Timestamp optDate;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    


    public Long getSellorderstotal() {
        return this.sellorderstotal;
    }
    
    public void setSellorderstotal(Long sellorderstotal) {
        this.sellorderstotal = sellorderstotal;
    }
    


    public Long getNormalorder() {
        return this.normalorder;
    }
    
    public void setNormalorder(Long normalorder) {
        this.normalorder = normalorder;
    }
    


    public Long getAlteredorder() {
        return this.alteredorder;
    }
    
    public void setAlteredorder(Long alteredorder) {
        this.alteredorder = alteredorder;
    }
    


    public Long getRefundorder() {
        return this.refundorder;
    }
    
    public void setRefundorder(Long refundorder) {
        this.refundorder = refundorder;
    }
    


    public Long getInvalidorder() {
        return this.invalidorder;
    }
    
    public void setInvalidorder(Long invalidorder) {
        this.invalidorder = invalidorder;
    }
    


    public Long getCancelorder() {
        return this.cancelorder;
    }
    
    public void setCancelorder(Long cancelorder) {
        this.cancelorder = cancelorder;
    }
    


    public Long getSoldticketCount() {
        return this.soldticketCount;
    }
    
    public void setSoldticketCount(Long soldticketCount) {
        this.soldticketCount = soldticketCount;
    }
    


    public java.math.BigDecimal getInamount() {
        return this.inamount;
    }
    
    public void setInamount(java.math.BigDecimal inamount) {
        this.inamount = inamount;
    }
    


    public java.math.BigDecimal getOutamount() {
        return this.outamount;
    }
    
    public void setOutamount(java.math.BigDecimal outamount) {
        this.outamount = outamount;
    }
    


    public java.math.BigDecimal getProfit() {
        return this.profit;
    }
    
    public void setProfit(java.math.BigDecimal profit) {
        this.profit = profit;
    }
    


    public java.math.BigDecimal getRefundamountreceived() {
        return this.refundamountreceived;
    }
    
    public void setRefundamountreceived(java.math.BigDecimal refundamountreceived) {
        this.refundamountreceived = refundamountreceived;
    }
    


    public java.math.BigDecimal getRefundamountpaid() {
        return this.refundamountpaid;
    }
    
    public void setRefundamountpaid(java.math.BigDecimal refundamountpaid) {
        this.refundamountpaid = refundamountpaid;
    }
    


    public java.math.BigDecimal getCancelticketcollection() {
        return this.cancelticketcollection;
    }
    
    public void setCancelticketcollection(java.math.BigDecimal cancelticketcollection) {
        this.cancelticketcollection = cancelticketcollection;
    }
    


    public java.math.BigDecimal getCancelticketrefund() {
        return this.cancelticketrefund;
    }
    
    public void setCancelticketrefund(java.math.BigDecimal cancelticketrefund) {
        this.cancelticketrefund = cancelticketrefund;
    }
    


    public java.sql.Timestamp getOptDate() {
        return this.optDate;
    }
    
    public void setOptDate(java.sql.Timestamp optDate) {
        this.optDate = optDate;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


